services:
  - type: web
    name: aguirre-server
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --no-deprecation
      - key: PORT
        value: 10000
      - key: PAYLOAD_SECRET
        value: your-secret-here-change-this
      - key: MONGODB_URI
        value: your-mongodb-uri-here
